version: '3.8'

services:
  # PostgreSQL для разработки
  postgres:
    image: postgres:15
    container_name: promocodes_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: promocodes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кеширования (опционально)
  redis:
    image: redis:7-alpine
    container_name: promocodes_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # pgAdmin для удобства разработки
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: promocodes_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_dev_data:
  redis_dev_data: